name: 'Publish OpenAPI Documentation'
description: 'Github action to have auto publish services OpenAPI documentation to centralized repo.'
inputs:
  service-name:
    description: 'Name of service.'
    required: true
  team-name:
    description: 'Name of team that owns service.'
    required: true
  file-output-path:
    description: 'Path to file that includes file name.  eg. /path/to/file.json'
    required: true
  centralized-openapi-spec-repo-deploy-private-key:
    description: 'Path to file that includes file name.  eg. /path/to/file.json'
    required: true
runs:
  using: "composite"
  steps:
    - name: Publish OpenAPI Documentation
      if: ${{ inputs.environment == 'production' }}
      shell: bash
      run: |
         eval `ssh-agent -s`
         ssh-add - <<< ${{ inputs.centralized-openapi-spec-repo-deploy-private-key }}
         git clone git@github.com:sdi-one-architecture/centralized-openapi-specs.git
         cp --force ${{ inputs.file-output-path }} centralized-openapi-specs/${{ inputs.team-name }}/
         cd centralized-openapi-specs
         git config --global user.email "sdi-devops-bot@one.singledigits.com"
         git config --global user.name "sdi-devops-bot"
         git add .
         if git diff-index --quiet HEAD; then
            echo "No changes to commit"
         else
            git commit -m "docs: Update OpenAPI specs for ${{ inputs.service-name }}"
            git push
         fi
